# Generated by Django 4.2.7 on 2023-11-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('due_date', models.DateField(max_length=20)),
                ('priority', models.CharField(max_length=200)),
                ('projectAssociation', models.CharField(max_length=200)),
            ],
        ),
    ]
